#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: 检查源码文件

env:
  REPO_URL: https://github.com/JHPatchouli/lede
  REPO_BRANCH: master

on:
  workflow_dispatch:
    inputs:
      trpath:
        description: '相对路径-如"./" "./bin" "./packages"'
        default: './'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: 克隆仓库
      id: Clone
      run: |
        git clone $REPO_URL
        
    - name: Feeds 检查更新 && 安装
      id: Feeds
      run: |
        cd lede && ./scripts/feeds update -a ./scripts/feeds install -a
      
    - name: 展示文件树 
      id: Show
      run: |
        cd ./lede && cd ${{ github.event.inputs.trpath }} && tree
